Repository Fuzzworth/simple_shell, pull requests merged in 2023-05, with the labels that each got.

#1 Added author file
  AUTHORS
Labels: documentation

#2 Update AUTHORS
  AUTHORS
Labels: documentation

#53 Update README.md
  README.md
Labels: documentation

#54 Simple Shell Exercise 4: V1
  _array_maker.c
  fork.c
  getline.c
  main.c
  main.h
Labels: enhancement, Exercises

#55 which function created with small bug
  .gitignore
  _array_maker.c
  _which.c
  main.c
  main.h
Labels: Exercises

#56 _which() fix: Added a copy of the path string because strtok was dest…
  _which.c
Labels: bug, enhancement, Exercises

#57 fix: betty documentation
  fork.c
Labels: documentation, Exercises

#58 added the print_env function
  _print_env.c
  fork.c
  main.c
  main.h
Labels: Exercises

#59 Added _getenv.c function
  _getenv.c
  main.c
  main.h
Labels: documentation, Exercises

#60 Build a linked list for the PATH directories
  add_nodetoken_end.c
  free_listkoken.c
  listkoken_len.c
  lists.h
  print_listkoken.c
Labels: Exercises

#61 Added _setenv.c function
  _setenv.c
  main.c
Labels: enhancement, Exercises

#62 Added _unsetenv function
  _unsetenv.c
  main.h
Labels: Exercises

#63 TASK 0: breaking build
  _array_maker.c
  _getenv.c
  _setenv.c
  _unsetenv.c
  _which.c
  add_nodetoken_end.c
  free_listkoken.c
  getline.c
  main.c
  main.h
  utility.c
Labels: Exercises

#66 Fix/valgrind read write issues
  AUTHORS
  _array_maker.c
  _getenv.c
  commands
  fork.c
Labels: bug

#67 Title: Fixed _WHICH memory Leaks
  _array_maker.c
  _which.c
Labels: bug

#68 Title: Fix
  main.c
Labels: bug

#69 Title: FIXED _GETENV and REFACTORED
  _array_maker.c
  _getenv.c
  fork.c
  main.c
  main.h
Labels: bug

#70 Title: Fix
  _which.c
  fork.c
  getline.c
  main.c
Labels: bug

#71 Title: Handle Ctrl + C
  getline.c
  main.c
  main.h
  prompt.c
  signal.c
Labels: bug

#72 Title: Handle Error and exit status
  _free.c
  _which.c
  digit.c
  error_handler.c
  fork.c
  getline.c
  main.c
  main.h
  string.c
Labels: bug, documentation, enhancement

#73 Title: Added Builtins
  _env_builtin.c
  _exit_builtin.c
  _free.c
  builtin_handler.c
  error_handler.c
  main.c
  main.h
Labels: documentation, enhancement

#74 Title: More fixes to main
  _which.c
Labels: bug, enhancement, Exercises

#75 small fix
  _which.c
Labels: bug

#76 Title: Fixed Non path binary exucuting in current directory
  _getenv.c
  _which.c
  main.h
Labels: bug, enhancement

#80 Title: Fixed path_path1_var.bash
  _which.c
Labels: bug, enhancement

#81 Title: Fixed exit_no_arg_1.bash
  main.c
Labels: bug, enhancement
